In [1]:
# importing 
import pandas as pd
from sqlalchemy import create_engine

In [2]:
# Store CSV into DataFrame
streaming_data = "MoviesOnStreaming.csv"
streaming_data_df = pd.read_csv(streaming_data)

In [3]:
streaming_data_df.head()

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Disney+,Directors,Genres,Country,Language,Runtime
0,1,Inception,2010,13+,8.8,87%,1,0,0,0,Christopher Nolan,"Action,Adventure,Sci-Fi,Thriller","United States,United Kingdom","English,Japanese,French",148.0
1,2,The Matrix,1999,18+,8.7,87%,1,0,0,0,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0
2,3,Avengers: Infinity War,2018,13+,8.5,84%,1,0,0,0,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0
3,4,Back to the Future,1985,7+,8.5,96%,1,0,0,0,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0
4,5,"The Good, the Bad and the Ugly",1966,18+,8.8,97%,1,0,1,0,Sergio Leone,Western,"Italy,Spain,West Germany",Italian,161.0

In [4]:
streaming_data_df.count()

ID                 16744
Title              16744
Year               16744
Age                 7354
IMDb               16173
Rotten Tomatoes     5158
Netflix            16744
Hulu               16744
Prime Video        16744
Disney+            16744
Directors          16018
Genres             16469
Country            16309
Language           16145
Runtime            16152
dtype: int64

In [5]:
# Dropping column name showed up in DF conflicting with PGADMIN DB.
streaming_data_df.drop(columns=['Disney+'],inplace = True)

In [6]:
streaming_na_df = streaming_data_df.dropna()

In [7]:
streaming_na_df.count()

ID                 3301
Title              3301
Year               3301
Age                3301
IMDb               3301
Rotten Tomatoes    3301
Netflix            3301
Hulu               3301
Prime Video        3301
Directors          3301
Genres             3301
Country            3301
Language           3301
Runtime            3301
dtype: int64

In [8]:
stm_us_df = streaming_na_df.loc[streaming_na_df["Country"] == "United States", :]

In [9]:
stm_us_df

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Directors,Genres,Country,Language,Runtime
1,2,The Matrix,1999,18+,8.7,87%,1,0,0,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",United States,English,136.0
2,3,Avengers: Infinity War,2018,13+,8.5,84%,1,0,0,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",United States,English,149.0
3,4,Back to the Future,1985,7+,8.5,96%,1,0,0,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",United States,English,116.0
5,6,Spider-Man: Into the Spider-Verse,2018,7+,8.4,97%,1,0,0,"Bob Persichetti,Peter Ramsey,Rodney Rothman","Animation,Action,Adventure,Family,Sci-Fi",United States,"English,Spanish",117.0
7,8,Django Unchained,2012,18+,8.4,87%,1,0,0,Quentin Tarantino,"Drama,Western",United States,"English,German,French,Italian",165.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16637,16638,Inspector Gadget 2,2003,all,3.4,40%,0,0,0,Alex Zamm,"Action,Comedy,Crime,Family,Sci-Fi",United States,English,89.0
16643,16644,Doug's 1st Movie,1999,all,5.0,26%,0,0,0,Maurice Joyce,"Animation,Adventure,Comedy,Drama,Family,Fantas...",United States,English,77.0
16677,16678,That Darn Cat,1997,7+,4.7,13%,0,0,0,Robert Stevenson,"Comedy,Crime,Family,Thriller",United States,"English,French",116.0
16687,16688,Kazaam,1996,7+,3.0,6%,0,0,0,Paul Michael Glaser,"Comedy,Family,Fantasy,Musical",United States,English,93.0
16705,16706,Meet the Deedles,1998,7+,4.1,7%,0,0,0,Steve Boyum,"Comedy,Family",United States,English,93.0

In [10]:
stm_us_df.drop(columns=['Country'],inplace = True)

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [11]:
stm_us_df.head()

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Directors,Genres,Language,Runtime
1,2,The Matrix,1999,18+,8.7,87%,1,0,0,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",English,136.0
2,3,Avengers: Infinity War,2018,13+,8.5,84%,1,0,0,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",English,149.0
3,4,Back to the Future,1985,7+,8.5,96%,1,0,0,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",English,116.0
5,6,Spider-Man: Into the Spider-Verse,2018,7+,8.4,97%,1,0,0,"Bob Persichetti,Peter Ramsey,Rodney Rothman","Animation,Action,Adventure,Family,Sci-Fi","English,Spanish",117.0
7,8,Django Unchained,2012,18+,8.4,87%,1,0,0,Quentin Tarantino,"Drama,Western","English,German,French,Italian",165.0

In [12]:
# Extracting % Rotten Tamatoes column
stm_us_df[stm_us_df.columns[5]] = stm_us_df[stm_us_df.columns[5]].replace('[%]', '', regex=True).astype(int)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [13]:
# Below codes are commented, it ran successfully.
# Converting Netflix, Hulu and Prime Videio value (0 and 1) into boolean data type (True and False)
# Netflix 
stm_us_df[stm_us_df.columns[6]] = stm_us_df[stm_us_df.columns[6]].replace('[1]',True, regex=True).astype(bool)
#Hulu
stm_us_df[stm_us_df.columns[7]] = stm_us_df[stm_us_df.columns[7]].replace('[1]',True, regex=True).astype(bool)
# Prime Video
stm_us_df[stm_us_df.columns[8]] = stm_us_df[stm_us_df.columns[8]].replace('[1]',True, regex=True).astype(bool)

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [14]:
stm_us_df.head()

,ID,Title,Year,Age,IMDb,Rotten Tomatoes,Netflix,Hulu,Prime Video,Directors,Genres,Language,Runtime
1,2,The Matrix,1999,18+,8.7,87,True,False,False,"Lana Wachowski,Lilly Wachowski","Action,Sci-Fi",English,136.0
2,3,Avengers: Infinity War,2018,13+,8.5,84,True,False,False,"Anthony Russo,Joe Russo","Action,Adventure,Sci-Fi",English,149.0
3,4,Back to the Future,1985,7+,8.5,96,True,False,False,Robert Zemeckis,"Adventure,Comedy,Sci-Fi",English,116.0
5,6,Spider-Man: Into the Spider-Verse,2018,7+,8.4,97,True,False,False,"Bob Persichetti,Peter Ramsey,Rodney Rothman","Animation,Action,Adventure,Family,Sci-Fi","English,Spanish",117.0
7,8,Django Unchained,2012,18+,8.4,87,True,False,False,Quentin Tarantino,"Drama,Western","English,German,French,Italian",165.0

In [15]:
stm_us_df.sort_values(by=['Title', 'Year'], ascending= True, inplace = True )

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [16]:
# Converting Upper case column name to lower case. 
stm_us_df.columns = map(str.lower, stm_us_df.columns)

In [17]:

# Removing space between column name 
stm_us_df = stm_us_df.rename(columns={"rotten tomatoes":"rotten_tomatoes", "prime video":"prime_video"})

In [18]:
#Final clean stream Data Frame and ready to load into pgadmin (SQL)
final_stream_df = stm_us_df.copy()

In [19]:
final_stream_df.head()

,id,title,year,age,imdb,rotten_tomatoes,netflix,hulu,prime_video,directors,genres,language,runtime
6674,6675,1 Night,2017,13+,5.8,33,False,False,True,Minhal Baig,"Drama,Romance",English,80.0
16442,16443,101 Dalmatians II: Patch's London Adventure,2003,all,5.8,67,False,False,False,"Jim Kammerud,Brian Smith","Animation,Adventure,Comedy,Family,Musical",English,74.0
5080,5081,11:55,2017,18+,4.9,100,False,False,True,"Ari Issler,Ben Snyder","Crime,Drama",English,80.0
1075,1076,13 Cameras,2015,18+,5.1,77,True,False,False,Victor Zarcoff,"Crime,Drama,Horror,Thriller",English,87.0
644,645,13 Sins,2014,18+,6.3,65,True,False,False,Daniel Stamm,"Horror,Thriller",English,93.0

In [20]:
final_stream_df["genres"] = final_stream_df.genres.str.split(",").str.get(0)

In [21]:
final_stream_df.head()

,id,title,year,age,imdb,rotten_tomatoes,netflix,hulu,prime_video,directors,genres,language,runtime
6674,6675,1 Night,2017,13+,5.8,33,False,False,True,Minhal Baig,Drama,English,80.0
16442,16443,101 Dalmatians II: Patch's London Adventure,2003,all,5.8,67,False,False,False,"Jim Kammerud,Brian Smith",Animation,English,74.0
5080,5081,11:55,2017,18+,4.9,100,False,False,True,"Ari Issler,Ben Snyder",Crime,English,80.0
1075,1076,13 Cameras,2015,18+,5.1,77,True,False,False,Victor Zarcoff,Crime,English,87.0
644,645,13 Sins,2014,18+,6.3,65,True,False,False,Daniel Stamm,Horror,English,93.0

In [22]:
final_stream_df.dtypes

id                   int64
title               object
year                 int64
age                 object
imdb               float64
rotten_tomatoes      int64
netflix               bool
hulu                  bool
prime_video           bool
directors           object
genres              object
language            object
runtime            float64
dtype: object

In [23]:
final_stream_df

,id,title,year,age,imdb,rotten_tomatoes,netflix,hulu,prime_video,directors,genres,language,runtime
6674,6675,1 Night,2017,13+,5.8,33,False,False,True,Minhal Baig,Drama,English,80.0
16442,16443,101 Dalmatians II: Patch's London Adventure,2003,all,5.8,67,False,False,False,"Jim Kammerud,Brian Smith",Animation,English,74.0
5080,5081,11:55,2017,18+,4.9,100,False,False,True,"Ari Issler,Ben Snyder",Crime,English,80.0
1075,1076,13 Cameras,2015,18+,5.1,77,True,False,False,Victor Zarcoff,Crime,English,87.0
644,645,13 Sins,2014,18+,6.3,65,True,False,False,Daniel Stamm,Horror,English,93.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5970,5971,Zombeavers,2014,18+,4.8,69,False,False,True,Jordan Rubin,Comedy,English,77.0
3568,3569,Zombieland,2009,18+,7.6,90,False,True,True,Ruben Fleischer,Adventure,English,88.0
2043,2044,Zoom,2006,7+,4.4,3,True,False,False,Peter Hewitt,Action,English,93.0
16225,16226,Zootopia,2016,7+,8.0,98,False,False,False,"Byron Howard,Rich Moore,Jared Bush",Animation,English,108.0
4529,4530,mid90s,2018,18+,7.4,81,False,False,True,Jonah Hill,Comedy,English,85.0

In [24]:
# Connecting to local database

netflix_connection_string = "admin1:12345@localhost:5432/Movie_Harless"
engine = create_engine(f'postgresql://{netflix_connection_string}')

In [25]:
# Pulling tables from database
engine.table_names()

['movie_search_project']

In [26]:
# Below code worked and loaded successfully into pgAdmin Database table. 
final_stream_df.to_sql(name='movie_search_project', con=engine, if_exists='append', index=False)

In [27]:
# Go to pgadmin to see if all data has been loaded.
pd.read_sql_query('select * from movie_search_project', con=engine).head()

,id,title,year,age,imdb,rotten_tomatoes,netflix,hulu,prime_video,directors,genres,language,runtime
0,6675,1 Night,2017,13+,5.8,33,False,False,True,Minhal Baig,Drama,English,80.0
1,5081,11:55,2017,18+,4.9,100,False,False,True,"Ari Issler,Ben Snyder",Crime,English,80.0
2,1076,13 Cameras,2015,18+,5.1,77,True,False,False,Victor Zarcoff,Crime,English,87.0
3,645,13 Sins,2014,18+,6.3,65,True,False,False,Daniel Stamm,Horror,English,93.0
4,88,13th,2016,18+,8.2,96,True,False,False,Ava DuVernay,Documentary,English,100.0